### ISSUE TITLE
Apply clippy and setup github actions

### ISSUE THREAD

**Issue by OTL** [openrr/k#57]

**Comment by OTL** [comment]
See https://github.com/openrr/openrr/blob/1fe74cd18991c362724bd02b7de8e746a905de57/.github/workflows/main.yml#L125

**Comment by ssr-yuki** [comment]
Ok

**Comment by ssr-yuki** [comment]
@OTL  Do you want only `clippy`? I can also apply `fmt`.

**Comment by OTL** [comment]
fmt!fmt!
